component_depth: 2
languages:
- name: php
  production:
      exclude:
          - /nlx-setup/.*
          - /resources/.*
          - /api/bin/.*
          - /api/config/.*
          - /api/docker/.*
          - /api/docs/.*
          - /api/helm/.*
          - /api/migrations/.*
          - /api/nlx-setup/.*
          - /api/public/.*
          - /api/templates/.*
          - /api/translations/.*
          - /api/var/.*
          - /api/vendor/.*
          - /api/src/Entity/.*
          - /api/src/Subscriber/.*
          - /api/src/Kernel.php

