version: '3.5'

x-cache:
  &cache
  cache_from:
    - ${CONTAINER_REGISTRY_BASE}/${CONTAINER_PROJECT_NAME}-php
    - ${CONTAINER_REGISTRY_BASE}/${CONTAINER_PROJECT_NAME}-nginx
    - ${CONTAINER_REGISTRY_BASE}/${CONTAINER_PROJECT_NAME}-ui

services:
  #  gateway-frontend:
  #    &gateway-frontend
  #    image: ghcr.io/conductionnl/commonground-gateway-frontend:latest
  #    depends_on:
  #      - php
  #    ports:
  #      - "83:80"
  
  ui:
    &ui
    image: ghcr.io/conductionnl/gateway-ui:stag
    depends_on:
      - api
    ports:
      - "8000:80"
    volumes:
      - ./ui/env.js:/usr/share/nginx/html/env.js:rw,cached
  php:
    &php
    image: ${CONTAINER_REGISTRY_BASE}/${CONTAINER_PROJECT_NAME}-php:${APP_ENV}
    build:
      context: ./api
      target: api_platform_php
      <<: *cache
    depends_on:
      - db
    volumes:
      - ./api:/srv/api:rw,cached
      - ./api/var/certs:/var/certs:rw,cached
      - ./gateway:/srv/api/fixtures:rw,cached
    environment:
      - CONTAINER_REGISTRY_BASE=${CONTAINER_REGISTRY_BASE}
      - CONTAINER_PROJECT_NAME=${CONTAINER_PROJECT_NAME}
      - DATABASE_URL=postgres://api-platform:!ChangeMe!@db/api?serverVersion=10.1
#      - DATABASE_URL=mysql://api-platform:!ChangeMe!@db/api?serverVersion=10.1
      - CACHE_URL=mongodb://api-platform:!ChangeMe!@mongodb
      - APP_ENV=${APP_ENV}
      - APP_CONTAINER=${APP_CONTAINER}
      - APP_DEBUG=${APP_DEBUG}
      - APP_CACHE=${APP_CACHE}
      - APP_VERSION=${APP_VERSION}
      - APP_NAME=${APP_NAME}
      - APP_NAME_TECHNICAL=${APP_NAME_TECHNICAL}
      - APP_DOMAIN=${APP_DOMAIN}
      - APP_SUBDOMAIN=${APP_SUBDOMAIN}
      - APP_SUBPATH=${APP_SUBPATH}
      - APP_SUBPATH_ROUTING=${APP_SUBPATH_ROUTING}
      - APP_DEMO=${APP_DEMO}
      - APP_REPRO=${APP_REPRO}
      - APP_DESCRIPTION=${APP_DESCRIPTION}
      - APP_LOGO=${APP_LOGO}
      - APP_HOME=${APP_HOME}
      - APP_COMMONGROUND_ID=${APP_COMMONGROUND_ID}
      - APP_APPLICATION_KEY=${APP_APPLICATION_KEY}
      - APP_BUILD_ALL_FIXTURES=${APP_BUILD_ALL_FIXTURES}
      - APP_WEB=${APP_WEB}
      - BADGES=${BADGES}
      - APP_BUILD=${APP_BUILD}
      - APP_INTERNAL=${APP_INTERNAL}
      - APP_URL=${APP_URL}
      - APP_CHART=${APP_CHART}
      - HELM_REPOSITORY=${HELM_REPOSITORY}
      - ARTIFACTHUB_ID=${ARTIFACTHUB_ID}
      - ARTIFACTHUB_USER=${ARTIFACTHUB_USER}
      - OWNER_NAME=${OWNER_NAME}
      - OWNER_URL=${OWNER_URL}
      - APP_SESSION_DURATION=${APP_SESSION_DURATION}
      - LICENCE_NAME=${LICENCE_NAME}
      - TRUSTED_PROXIES=${TRUSTED_PROXIES}
      - TRUSTED_HOSTS=${TRUSTED_HOSTS}
      - AUTH_ENABLED=${AUTH_ENABLED}
      - AUDITTRAIL_ENABLED=${AUDITTRAIL_ENABLED}
      - NOTIFICATION_ENABLED=${NOTIFICATION_ENABLED}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APP_AUTH=${APP_AUTH}
      - GITHUB_KEY=${GITHUB_KEY}
      - PUBLICCODE=${PUBLICCODE}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - READ_ONLY=false
      - DOCUMENTATION_TITLE=${DOCUMENTATION_TITLE}
      - DOCUMENTATION_DESCRIPTION=${DOCUMENTATION_DESCRIPTION}
      - DOCUMENTATION_TERMS_OF_SERVICE=${DOCUMENTATION_TERMS_OF_SERVICE}
      - DOCUMENTATION_CONTACT_NAME=${DOCUMENTATION_CONTACT_NAME}
      - DOCUMENTATION_CONTACT_URL=${DOCUMENTATION_CONTACT_URL}
      - DOCUMENTATION_CONTACT_EMAIL=${DOCUMENTATION_CONTACT_EMAIL}
      - DOCUMENTATION_LICENCE_NAME=${DOCUMENTATION_LICENCE_NAME}
      - DOCUMENTATION_LICENCE_URL=${DOCUMENTATION_LICENCE_URL}
      - DOCUMENTATION_VERSION=${DOCUMENTATION_VERSION}
      - CRON_RUNNER_ENABLED=${CRON_RUNNER_ENABLED}
      - CRON_RUNNER_CRONTAB=${CRON_RUNNER_CRONTAB}
      - CRON_RUNNER_CONCURRENCY_POLICY=${CRON_RUNNER_CONCURRENCY_POLICY}
    ports:
      - "82:80"
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges

  api:
    &nginx
    image: ${CONTAINER_REGISTRY_BASE}/${CONTAINER_PROJECT_NAME}-nginx:${APP_ENV}
    build:
      context: ./api
      target: api_platform_nginx
      dockerfile: Dockerfile-nginx
      <<: *cache
    depends_on:
      - php
    volumes:
      - ./api/public:/srv/api/public:ro
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=php
      - NGINX_ENV=${APP_ENV}
    cap_drop:
      - ALL
    cap_add:
      - chown
      - dac_override
      - setgid
      - setuid
      - net_bind_service
    security_opt:
      - no-new-privileges

  # helmPackage:
  #   image: alpine/helm:3.2.1
  #   volumes:
  #     - ./api/helm:/apps
  #   command: package /apps

  # helmIndex:
  #   depends_on:
  #     - helmPackage
  #   image: alpine/helm:3.2.1
  #   volumes:
  #     - ./api/helm:/apps
  #   command: repo index /apps

  redis:
    image: redis:4-alpine
  
# MySQL database:
#  db:
#    image: mysql:5.7
#    environment:
#      - MYSQL_ROOT_PASSWORD=example
#      - MYSQL_DATABASE=api
#      - MYSQL_USER=api-platform
#      - MYSQL_PASSWORD=!ChangeMe!
#    volumes:
#      - db-mysql:/var/lib/mysql:rw
#    ports:
#      - "3366:3306"

#  Postgres db:
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=api-platform
      - POSTGRES_PASSWORD=!ChangeMe!
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: api-platform
      MONGO_INITDB_ROOT_PASSWORD: '!ChangeMe!'
    ports:
      - "27017:27017"
        
  user-component:
    image: ghcr.io/conductionnl/user-component-nginx:latest
    depends_on: 
      - user-component-php
    environment:
      - NGINX_HOST=user-component-php
  
  user-component-php:
    image: ghcr.io/conductionnl/user-component-php:dev
    depends_on:
      - user-component-postgres
    volumes:
      - ./user-component:/srv/api/fixtures:rw,cached
    environment:
      - APP_ENV=dev
      - APP_APPLICATION_KEY=45c1a4b6-59d3-4a6e-86bf-88a872f35845
      - APP_CACHE=true
      - APP_DEBUG=0
      - APP_URL=http://user-component
      - APP_VERSION=V2.0
      - CASE_INSENSITIVE_USERNAME=true
      - DATABASE_URL=postgres://user-component:!ChangeMe!@user-component-postgres/uc?serverVersion=10.1
      - PASSWORD_STRENGTH=1
      - PRIVATE_KEY=LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV3QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktvd2dnU21BZ0VBQW9JQkFRRFNQU1lacUs3cHdMTWQKd0VqSThkeTA2aVUzQUxESHFOMnBvbmJEb0tIN09KcFVpa0hkT09NVVhNYUhGOWwyb0ZBQmV1VnkrMjJlVHZTQwp3SGdFeUlkTlBEOHhnaWcrUVFlLzBEZlNIaWxGK01ZNGJYbzBUdW0wbDB1MFRDMDNqSUMvUHdiWmJkd3AyczdmClo5TVh1dzdZdnpLS2dzSTdXWWhlSGxGazlkQXc4OUg4SjVUbkY2N050YkdWRkdYTUk5ekpSejZ6N3JRUzJGMjEKcmIyanNhMU4yWkliZW5rbmFrQjdmTEk2VU1mVk5DTXBVZHdERUN6TXNTUTQ4L2dvMzdJYjhzbElGZ2NTUWcrNgp4U1JleG1BT0lBUDIxSitnVjZubGhiMGQ2V2VCcUliQ1hoYkhoY0RGc3NiVGlyTms5UElCcm1FdktGU1prdVV2Cks4Z0hzTituQWdNQkFBRUNnZ0VCQUlFZ1JaSms1R2wxalkyc1dBZnpaUmRJNkdxTDVnZjdVNG1vMjBEMEhBanMKanYxMW5WWitaaHBQa1MvUUdpU2QrZ1d1c2RhWlRvNTQ5L3lHc2pCZDZad3FjTFc3dDNQbEJSbHVqWnBrSS8xeAorbTBWOElUSUl3cGtFbjgrZWxjdjJMT2R4bHNzK3BoS1o5MFhLN1BibEJiVDkvclNyUEUrNEY3T1NEZTJNcFNkClRvVi9XQis1SC90eFM1TVpIRHM3OTA3RFpLemdkdUZyVHBPRUZQeUp3MnoxbWNRbzhnK2ZTbm90Q1ZncUFFRFcKcXFSNHpmK05WTUdId3A3WC9Lc3k1eWdkZnZ3QXpaVEVaUmFzVHVnN1JDdHhyVUp0d2lEMk9rdmNoMzNXYzA1VQoyVnVqdmk5ODhuY1hWeVZOOG8wbnU4aUNRV25veUM5SnJDRnlTU000cjJFQ2dZRUEraWJJb2E2aHlGNkNIcFYxCk9uYmIwT2ZleVhMS01vTkNDN2FYdXFHUVBsTG52K3FXUFJqRXdWR3Mvb3NrS2hFRWhsSEdvamc1dkhSQ1g2T3AKSTlJSis4U201d08xSlJFUFFNdmdza0ZWR3NlZVF5UXNYajJmRmp5cDZ4RGhHMlFzNlFpZHRuZEN6L1hOZWxBQQowNmVkbHl0L0I3Z1d1dWtoYWQ1SjhrT3UzeVVDZ1lFQTF5ZDZmYkhtNFQyMmkxQXZYYTBaSG8rME1oZUVGYTg0ClpaZXVtSmNKaTd3NnFjR016ejkwNno5V0lPT3ZvTk9WZWdVOHMvb2labUZiMXZ3bmE2SnJRZWpid0ZJckN0TlIKYlF3SmsrVkIrY0RJckxtTjhuclBacVM0THY0Y3hOOWlMYWtVMlpid1Jrb1NQSldlaUM2SWt5SWNEYzVxTVpCZwpubTJxSVlxQW45c0NnWUVBbEZwNTlFRlFHemZKYlgvdjFTdDJjKzkvbGZNbzdVb2cyamVBeHFOWW0wMnB1WXpUCmF3cU1iYVlWdGFRcFgzVldQSjYwOGJIc3M5SXpKdXMxdlZPc3JnN1RlUUFlNXd1MkF4U21mckQyV3ZwMTVwWEcKWm1HZlBwM2RtOVlYMnBuUGRLaXlkK3RFeVhhYVZPYXJodHJLUUVRQWcwQnU0b3l1VDA0UWhzZ1RKcTBDZ1lFQQpuWmRTRmkwdmduM1VibGh1U1R3WHNSWHJFK0c3b3JKMEtaMmZpaTdmRkJYc0Zoa3B6VWVhbVJFTVFnemp3SFlaCi80VkVnRU5QM1JPazFHUmZiMnhKQ2I3STd5YUFWbTZRTHNKcFpZVy8vSEtqeWpnamE1OWV1TDBnRjNPVG1QUlMKRWtYTmVzOGU4UzBpREhRKzZWckVPSmo4V1hSK3ZnMFZhQlhGVHNvSENvOENnWUVBOWhpRVlVTXZFNTdQMytmSgptZmZSMytwamJ6WDF0dWY2K0FqcGFrTjNodDFhWUJmaXJzRTlDTHpZdVBqSW4zdU1DRWZvdVFkMGc3c01UcGJnCmxBVXlkaWNPMFNvdDNmSHBLV0F5R3laOVRWYlhIaGUrb1FJYUN1VWFaanlQSFFPWWhHTzZwV0ZDam9aV01JZUwKZjBGcVg0UFExZEJPd3drNDl2Vm16YTJIY1RzPQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
      - PUBLIC_KEY=LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ4VENDQXRtZ0F3SUJBZ0lVVTlMMXFhdGI5WndXTGd4Rlg1VHB0bjNiQytjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZY3hDekFKQmdOVkJBWVRBazVNTVJZd0ZBWURWUVFJREExT2IyOXlaQ0JJYjJ4c1lXNWtNUkl3RUFZRApWUVFIREFsQmJYTjBaWEprWVcweEV6QVJCZ05WQkFvTUNrTnZibVIxWTNScGIyNHhFakFRQmdOVkJBTU1DV3h2ClkyRnNhRzl6ZERFak1DRUdDU3FHU0liM0RRRUpBUllVY205aVpYSjBRR052Ym1SMVkzUnBiMjR1Ym13d0hoY04KTWpFd09UQXlNRGMxTWpVd1doY05Nakl3T1RBeU1EYzFNalV3V2pDQmh6RUxNQWtHQTFVRUJoTUNUa3d4RmpBVQpCZ05WQkFnTURVNXZiM0prSUVodmJHeGhibVF4RWpBUUJnTlZCQWNNQ1VGdGMzUmxjbVJoYlRFVE1CRUdBMVVFCkNnd0tRMjl1WkhWamRHbHZiakVTTUJBR0ExVUVBd3dKYkc5allXeG9iM04wTVNNd0lRWUpLb1pJaHZjTkFRa0IKRmhSeWIySmxjblJBWTI5dVpIVmpkR2x2Ymk1dWJEQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQwpBUW9DZ2dFQkFOSTlKaG1vcnVuQXN4M0FTTWp4M0xUcUpUY0FzTWVvM2FtaWRzT2dvZnM0bWxTS1FkMDQ0eFJjCnhvY1gyWGFnVUFGNjVYTDdiWjVPOUlMQWVBVEloMDA4UHpHQ0tENUJCNy9RTjlJZUtVWDR4amh0ZWpSTzZiU1gKUzdSTUxUZU1nTDgvQnRsdDNDbmF6dDluMHhlN0R0aS9Nb3FDd2p0WmlGNGVVV1QxMEREejBmd25sT2NYcnMyMQpzWlVVWmN3ajNNbEhQclB1dEJMWVhiV3R2YU94clUzWmtodDZlU2RxUUh0OHNqcFF4OVUwSXlsUjNBTVFMTXl4CkpEanorQ2pmc2h2eXlVZ1dCeEpDRDdyRkpGN0dZQTRnQS9iVW42QlhxZVdGdlIzcFo0R29oc0plRnNlRndNV3kKeHRPS3MyVDA4Z0d1WVM4b1ZKbVM1UzhyeUFldzM2Y0NBd0VBQWFOVE1GRXdIUVlEVlIwT0JCWUVGRlRRbENzNwo3c1RzTXF1V3dCUjFORXZndWRYVk1COEdBMVVkSXdRWU1CYUFGRlRRbENzNzdzVHNNcXVXd0JSMU5Fdmd1ZFhWCk1BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFJV3ZpZldiV3FQNklUd20KS1d2YW9Lc1JIc1BzZ0dxYUF2OXlkZ24xSVp2WFQzZGg3eXpOdHFJRXNDcHpvc2c0Zis3Rlo2bG5GZHI2RFZVbgpmMGh3bUV4ems3d1lYdjBtd2xCTHg1alJmb0tKbDA2SFdkVHVFYUJwR2JYR1Y3VHZjQ3dEb1hYenlYYkljT1FqCnFMeGM0RlE5dlZXazRQM0Y1dDZ6dFh3TWVYWDhZeVYwaGN4cXRaVHNsL25ZVDFvc2pKUlBlWDBRRXFXTjJKZ1QKTGFwckNwK0ZOOXI2WlRwb3EybXVwNmcxTE9HaW1md1k3VDR4elhEaUNlMk1FMi93azBuczBpZXFmeFpwQk5mMApaYitZTHBPekVIYmNlS3dqSEJxT016VlJTZy93bW9sN05VWEF5YkZUNlMwaU5EQWlVSUJ6Q2xUZDhPQ0ZlYXB6CmdwYmROaDA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    
    
  user-component-postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=uc
      - POSTGRES_USER=user-component
      - POSTGRES_PASSWORD=!ChangeMe!
    volumes:
      - uc-data:/var/lib/postgresql/data:rw

  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

networks:
  nlx:
    name: nlx

volumes:
  db-data: {}
  db-mysql: {}
  uc-data: {}
  nlx-data-2: {}
