site_name: Common Gateway
site_url: https://docs.conductor-gateway.app
repo_url: https://github.com/ConductionNL/commonground-gateway/
docs_dir: redoc/docs

nav:
    - Home: "index.md"
    - Getting Started: "getting_started.md"
    - How does it work: "how_does_it_work.md"
    - Features:  "./features/index.md"
    - Api: "api.md"
    - Endpoints: "endpoints.md"
    - Plugins: "plugins.md"
    - Schemas: "schemas.md"
    - Mappings: "mappings.md"
    - Design Decisions: "design_decisions.md"
    - Contributing: "contributing.md"
    - Installation: "installation.md"
    - Security: "security.md"

theme:
    name: readthedocs

