site_name: Common Gateway
site_url: https://docs.conductor-gateway.app
repo_url: https://github.com/ConductionNL/commonground-gateway/
docs_dir: redoc/docs

nav:
    - "index.md"
    - "getting_started.md"
    - "how_does_it_work.md"
    - Features: "./features/index.md"
    - "plugins.md"
    - "schemas.md"
    - "design_decisions.md"
    - "contributing.md"
    - "installation.md"
    - "security.md"

theme:
    name: readthedocs

