parameters:
  env(DIGID_ENABLED): "true"

  env(DIGID_METADATA_LOCATION): "https://digispoof.common-ground.dev/saml/metadata"
  env(DIGID_SIGN_ON_URL): "https://digispoof.common-ground.dev/"
  env(DIGID_LOGOUT_URL): "https://digispoof.common-ground.dev"
  env(DIGID_IDP_CERT): "/var/certs/idp.crt"
  env(DIGID_ARTIFACT_METHOD): "Artifact"
  env(DIGID_ARTIFACT_URL): 'https://digispoof.common-ground.dev/artifact'

  digidArtifactUrl: "%env(DIGID_ARTIFACT_URL)%"

  digid_x509_cert: "%env(default::file:DIGID_IDP_CERT)%"

  digid_login_url: "%env(DIGID_SIGN_ON_URL)%"
  digid_logout_url: "%env(DIGID_LOGOUT_URL)%"
  digid_metadata_url: "%env(DIGID_METADATA_LOCATION)%"

  digid_enabled: "%env(bool:DIGID_ENABLED)%"

  env(DIGID_CERTIFICATE): "%env(default:digid_default:file:APP_CERT)%"
  env(DIGID_PRIVATEKEY): "%env(default:digid_default:file:APP_KEY)%"
  env(DIGID_IDP_CERTIFICATE): "%env(default:digid_default:file:DIGID_IDP_CERT)%"

  digid_default: "abcd"

digid:
  idp:
    entityId: "%env(DIGID_METADATA_LOCATION)%"
    singleSignOnService:
      url: "%env(DIGID_SIGN_ON_URL)%"
      binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
    singleLogoutService:
      url: "%env(DIGID_LOGOUT_URL)%"
      binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
    x509cert: "%env(DIGID_IDP_CERTIFICATE)%"
  sp:
    entityId: "%env(trimtrailingslash:APP_URL)%/saml"
    assertionConsumerService:
      url: "%env(trimtrailingslash:APP_URL)%/digid/SLO/artifact"
      binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-%env(DIGID_ARTIFACT_METHOD)%"
    singleLogoutService:
      url: "%env(trimtrailingslash:APP_URL)%/digid/logout"
      binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
    privateKey: "%env(DIGID_PRIVATEKEY)%"
    x509cert: "%env(DIGID_CERTIFICATE)%"
  # Optional settings
  baseurl: "%env(APP_URL)%"
  strict: false
  debug: true
  security:
    nameIdEncrypted: false
    authnRequestsSigned: true
    logoutRequestSigned: false
    logoutResponseSigned: false
    wantMessagesSigned: false
    wantAssertionsSigned: false
    wantNameIdEncrypted: false
    requestedAuthnContext:
      - "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport"
    signMetadata: true
    wantXMLValidation: true
    signatureAlgorithm: "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"
    digestAlgorithm: "http://www.w3.org/2001/04/xmlenc#sha256"
