parameters:
    env(SAML_ENABLED): 'false'

    env(SAML_METADATA_LOCATION): 'https://example.com/saml/metadata'
    env(SAML_SIGN_ON_URL): 'https://example.com/saml2'
    env(SAML_LOGOUT_URL): 'https://example.com/saml2'
    env(SAML_IDP_CERT): ''
    env(APP_CERT): '/var/certs/certificate.crt'
    env(APP_KEY): '/var/certs/certificate.key'
    env(SAML_ARTIFACT_METHOD): 'POST'

    artifactUrl: 'https://digispoof.common-ground.dev/artifact'
    app_cert: '%env(APP_CERT)%'
    app_key: '%env(APP_KEY)%'
    app_x509_cert: '%env(default::file:APP_CERT)%'
    app_rsa_key: '%env(default::file:APP_KEY)%'

    saml_x509_cert: '%env(default::file:SAML_IDP_CERT)%'

    saml_login_url: "%env(SAML_SIGN_ON_URL)%"
    saml_logout_url: "%env(SAML_LOGOUT_URL)%"
    saml_metadata_url: "%env(SAML_METADATA_LOCATION)%"

    saml_enabled: '%env(bool:SAML_ENABLED)%'

    env(SAML_CERTIFICATE): '%env(default:saml_default:file:APP_CERT)%'
    env(SAML_PRIVATEKEY): '%env(default:saml_default:file:APP_KEY)%'
    env(SAML_IDP_CERTIFICATE): '%env(default:saml_default:file:SAML_IDP_CERT)%'
    
    saml_default: 'abcd'


saml:
    idp:
        entityId: '%env(SAML_METADATA_LOCATION)%'
        singleSignOnService:
            url: '%env(SAML_SIGN_ON_URL)%'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
        singleLogoutService:
            url: '%env(SAML_LOGOUT_URL)%'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
        x509cert: '%env(SAML_IDP_CERTIFICATE)%'
    sp:
        entityId: '%env(trimtrailingslash:APP_URL)%/saml'
        assertionConsumerService:
            url: '%env(trimtrailingslash:APP_URL)%/saml/SLO/artifact'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-%env(SAML_ARTIFACT_METHOD)%'
        singleLogoutService:
            url: '%env(trimtrailingslash:APP_URL)%/saml/logout'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
        privateKey: '%env(SAML_PRIVATEKEY)%'
        x509cert: '%env(SAML_CERTIFICATE)%'
    # Optional settings
    baseurl: '%env(APP_URL)%'
    strict: false
    debug: true
    security:
        nameIdEncrypted:       false
        authnRequestsSigned:   true
        logoutRequestSigned:   false
        logoutResponseSigned:  false
        wantMessagesSigned:    false
        wantAssertionsSigned:  false
        wantNameIdEncrypted:   false
        requestedAuthnContext:
            - 'urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport'
        signMetadata: true
        wantXMLValidation: true
        signatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
        digestAlgorithm: 'http://www.w3.org/2001/04/xmlenc#sha256'
