doctrine:
    dbal:
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        charset: UTF-8
        url: '%env(resolve:DATABASE_URL)%'
        options:
            TrustServerCertificate: true
            Encrypt: false
        types:
            uuid:  Ramsey\Uuid\Doctrine\UuidType
            datetime:  Conduction\CommonGroundBundle\Types\UTCDateTimeType  #We override the default doctrine datetime with a UTC based version
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                regexp_replace: DoctrineExtensions\Query\Postgresql\RegexpReplace
