#App\Entity\Endpoint:
#    stufZaken:
#        name: StUF zaken endpoint
#        description: Endpoint for StUF zaken
#        path:
#            - 'stuf'
#            - 'zaken'
#        pathRegex: "^(stuf/zaken)$"
#        operationType: collection
#        method: 'POST'
#
#    stufHaalZaken:
#        name: StUF zaken endpoint
#        description: Endpoint for StUF zaken
#        path:
#            - 'stuf'
#            - 'haalzaken'
#        pathRegex: "^(stuf/haalzaken)$"
#        operationType: collection
#        method: 'POST'
#
#    stufDocumenten:
#        name: StUF zaken endpoint
#        description: Endpoint for StUF zaken
#        path:
#            - 'stuf'
#            - 'documenten'
#        pathRegex: "^(stuf/documenten)$"
#        operationType: collection
#        method: 'POST'
#
#App\Entity\Gateway:
#    zrc_gateway:
#        name: open-zaak
#        location: https://test-guh-openzaak.contezza.cloud/zaken/api/v1
#        auth: jwt-HS256
#        jwtId: sim-62uplKQC
#        secret: '3ynPYS98JgZ8STkN69e6ud4AXLcSl7VX' #offcourseIwillnottellyoumysecret
#        accept: application/json
#
#    ztc_gateway:
#        name: open-zaak
#        location: https://test-guh-openzaak.contezza.cloud/catalogi/api/v1
#        auth: jwt-HS256
#        accept: application/json
#        jwtId: sim-62uplKQC
#        secret: '3ynPYS98JgZ8STkN69e6ud4AXLcSl7VX' #offcourseIwillnottellyoumysecret
#
#App\Entity\CollectionEntity:
#    zrc:
#        name: zaken
#        description: 'ZGW zaken'
#        locationOAS: "https://test-guh-openzaak.contezza.cloud/zaken/api/v1/schema/openapi.json"
#        source: '@zrc_gateway'
#        sourceUrl: "https://github.com/ConductionNL/zrc_publiccode"
#        sourceType: "url"
#        autoload: true
#    ztc:
#        name: catalogi
#        description: 'ZGW catalogi'
#        locationOAS: "https://test-guh-openzaak.contezza.cloud/catalogi/api/v1/schema/openapi.json"
#        source: '@ztc_gateway'
#        sourceUrl: "https://github.com/ConductionNL/ztc_publiccode"
#        sourceType: "url"
#        autoload: true
#
#App\Entity\Application:
#    application:
#        domains:
#            - acc-utrechtse-heuvelrug.commonground.nu
#        name: utrechtse heuvelrug
#        organization: http://api/api/organizations/a1c8e0b6-2f78-480d-a9fb-9792142f4761
#
#App\Entity\Handler:
#    zakenHalenHandler:
#        name: zakenhalenhandler
#        methods: ["*"]
#        sequence: 0
#        conditions: "{}"
#        endpoints: ['@stufHaalZaken']
#        entity: '@stufSkeleton'
#        translationsOut:
#            - caseTable1
#            - caseTable2
#        mappingOut:
#            SOAP-ENV:Envelope.SOAP-ENV:Body.ZKN:zakLa01.ZKN:antwoord.ZKN:object: object(s) | array
#            SOAP-ENV:Envelope.SOAP-ENV:Body.ZKN:zakLa01.ZKN:antwoord.ZKN:object.$.ZKN:heeft.ZKN:gerelateerde: "results.ZKN:$.ZKN:status"
#            SOAP-ENV:Envelope.SOAP-ENV:Body.ZKN:zakLa01.ZKN:antwoord.ZKN:object.$.ZKN:isVan.ZKN:gerelateerde: "results.ZKN:$.ZKN:zaaktype"
#        methodOverrides:
#            POST:
#                - method: GET
#                  condition: SOAP-ENV:Body.ns2:zakLv01.ns2:gelijk.ns2:identificatie
#                  operationType: item
#                  pathValues:
#                      '{identificatie}': SOAP-ENV:Body.ns2:zakLv01.ns2:gelijk.ns2:identificatie
#                - method: GET
#                  operationType: collection
#                  condition: SOAP-ENV:Body.ns2:zakLv01.ns2:gelijk.ns2:heeftAlsInitiator.ns2:gerelateerde.ns2:identificatie
#                  forceSynchronisation: true
#                  queryParameters:
#                      '@bsn': SOAP-ENV:Body.ns2:zakLv01.ns2:gelijk.ns2:heeftAlsInitiator.ns2:gerelateerde.ns2:identificatie
#        prefix: "ZKN:"
#        skeletonOut:
#            SOAP-ENV:Envelope:
#                '@xmlns:SOAP-ENV': 'http://schemas.xmlsoap.org/soap/envelope/'
#                '@xmlns:ZKN': "http://www.egem.nl/StUF/sector/zkn/0310"
#                '@xmlns:StUF': "http://www.egem.nl/StUF/StUF0301"
#                '@xmlns:xsi': "http://www.w3.org/2001/XMLSchema-instance"
#                '@xmlns:BG': "http://www.egem.nl/StUF/sector/bg/0310"
#                'SOAP-ENV:Header': null
#                'SOAP-ENV:Body':
#                    'ZKN:zakLa01':
#                        'ZKN:stuurgegevens':
#                            'StUF:berichtcode': La01
#                            'StUF:zender':
#                                'StUF:applicatie': CGM
#                            'StUF:ontvanger':
#                                'StUF:organisatie': SIM
#                                'StUF:applicatie': simsite
#                            'StUF:referentienummer': MK6B3B
#                            'StUF:tijdstipBericht': 2022040411363332
#                            'StUF:crossRefnummer': 6864340232
#                            'StUF:entiteittype': ZAK
#                        'ZKN:parameters':
#                            'StUF:indicatorVervolgvraag': false
#                        'ZKN:antwoord':
#                            'ZKN:object':
#                                '@StUF:entiteittype': ZAK
#                                '@StUF:sleutelVerzendend': 54602
#                                '@StUF:sleutelGegevensbeheer': 54602
#                                '#': {}
#    zakenBrengenHandler:
#        name: zakenbrengenhandler
#        methods: ['*']
#        sequence: 0
#        conditions: '{}'
#        endpoints: ['@stufZaken']
#        entity: #zaken entity
#        mappingIn:
#            omschrijving: SOAP-ENV:Body.ns2:zakLk01.ns2:object.ns2:omschrijving
#            toelichting: SOAP-ENV:Body.ns2:zakLk01.ns2:object.ns2:toelichting
#            registratiedatum: SOAP-ENV:Body.ns2:zakLk01.ns2:object.ns2:registratiedatum | date
#            startdatum: SOAP-ENV:Body.ns2:zakLk01.ns2:object.ns2:startdatum | date
#            einddatumGepland: SOAP-ENV:Body.ns2:zakLk01.ns2:object.ns2:einddatumGepland | date
#            uiterlijkeEinddatumAfdoening: SOAP-ENV:Body.ns2:zakLk01.ns2:object.ns2:uiterlijkeEinddatum | date
#            publicatiedatum: SOAP-ENV:Body.ns2:zakLk01.ns2:object.ns2:publicatiedatum | date
#            betalingsindicatie: SOAP-ENV:Body.ns2:zakLk01.ns2:object.ns2:betalingsIndicatie
#            laatsteBetaaldatum: SOAP-ENV:Body.ns2:zakLk01.ns2:object.ns2:laatsteBetaaldatum | date
#        skeletonIn:
#            archiefstatus: 'nog_te_archiveren'
#            bronorganisatie: '999990639'
#            verantwoordelijkeOrganisatie: '999993653'
#            zaaktype: https://test-guh-openzaak.contezza.cloud/catalogi/api/v1/zaaktypen/859697ee-c467-4270-b3f1-10875b65ab13
#        skeletonOut:
#            SOAP-ENV:Envelope:
#                '@xmlns:SOAP-ENV': http://schemas.xmlsoap.org/soap/envelope/
#                SOAP-ENV:Body:
#                    StUF:Bv03Bericht:
#                        '@xmlns:StUF': http://www.egem.nl/StUF/StUF0301
#                        StUF:stuurgegevens:
#                            StUF:berichtcode: Bv03
#                            StUF:zender:
#                                StUF:applicatie: CGS
#                            StUF:ontvanger:
#                                StUF:applicatie: SIMform
#                            StUF:referentienummer: '00000004'
#                            StUF:tijdstipbericht: '202207220913'
#                            StUF:crossRefnummer: '1572191056'
#
#App\Entity\Entity:
#    stufSkeleton:
#        name: stufSkeleton
#        description: An entity for the StUF Skeleton
#
#App\Entity\Translation:
#    kenmerkTranslation:
#        translationTable: caseTable1
#        translateFrom: kenmerken
#        translateTo: kenmerk
#        language: en
#    uiterlijkeEinddatumAfdoeningTranslation:
#        translationTable: caseTable2
#        translateFrom: uiterlijkeEinddatumAfdoening
#        translateTo: uiterlijkeEinddatum
#        language: en
#
#App\Entity\Action:
#    zaaktypeAction:
#        name: ZaakTypeAction
#        priority: 0
#        async: false
#        class: App\ActionHandler\ZaakTypeHandler
#        listens:
#            - 'commongateway.handler.pre'
#        configuration:
#            identifierPath: SOAP-ENV:Body.ns2:zakLk01.ns2:object.ns2:isVan.ns2:gerelateerde.ns2:omschrijving
#            entityId: blablabla
#        conditions:
#            var: request.SOAP-ENV:Body.ns2:zakLk01
#
#    zaakeigenschappenAction:
#        name: ZaakEigenschappenAction
#        priority: 0
#        async: false
#        class: App\ActionHandler\ZaakEigenschappenHandler
#        listens:
#            - 'commongateway.handler.post'
#        configuration:
#            identifierPath: SOAP-ENV:Body.ns2:zakLk01.ns2:object.ns2:isVan.ns2:gerelateerde.ns2:omschrijving
#            eigenschappen: SOAP-ENV:Body.ns2:zakLk01.ns2:object.ns1:extraElementen
#        conditions:
#            var: request.SOAP-ENV:Body.ns2:zakLk01
