{{- if .Values.security.rootCA }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "commonground-gateway.fullname" . }}-rootca
  labels:
    {{- include "commonground-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
    ca.crt: |
        {{ .Values.security.rootCA | nindent 8 }}
{{- end }}
