<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20230221122059 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE action_handler (id UUID NOT NULL, class VARCHAR(255) NOT NULL, configuration TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN action_handler.configuration IS \'(DC2Type:simple_array)\'');
        $this->addSql('CREATE TABLE application (id UUID NOT NULL, organization_id UUID NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, domains TEXT NOT NULL, public_column TEXT DEFAULT NULL, secret TEXT DEFAULT NULL, public_key TEXT DEFAULT NULL, private_key TEXT DEFAULT NULL, resource VARCHAR(255) DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, certificates TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A45BDDC132C8A3DE ON application (organization_id)');
        $this->addSql('COMMENT ON COLUMN application.domains IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN application.certificates IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE application_endpoint (application_id UUID NOT NULL, endpoint_id UUID NOT NULL, PRIMARY KEY(application_id, endpoint_id))');
        $this->addSql('CREATE INDEX IDX_7B79D0683E030ACD ON application_endpoint (application_id)');
        $this->addSql('CREATE INDEX IDX_7B79D06821AF7E36 ON application_endpoint (endpoint_id)');
        $this->addSql('CREATE TABLE attribute (id UUID NOT NULL, entity_id UUID DEFAULT NULL, search_partial_id UUID DEFAULT NULL, object_id UUID DEFAULT NULL, inversed_by_id UUID DEFAULT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, format VARCHAR(255) DEFAULT NULL, multiple BOOLEAN NOT NULL, function_column VARCHAR(255) DEFAULT \'noFunction\' NOT NULL, extend BOOLEAN DEFAULT \'false\' NOT NULL, include BOOLEAN DEFAULT \'false\' NOT NULL, multiple_of INT DEFAULT NULL, maximum INT DEFAULT NULL, exclusive_maximum BOOLEAN DEFAULT NULL, minimum INT DEFAULT NULL, exclusive_minimum BOOLEAN DEFAULT NULL, max_length INT DEFAULT NULL, min_length INT DEFAULT NULL, max_items INT DEFAULT NULL, min_items INT DEFAULT NULL, unique_items BOOLEAN DEFAULT NULL, max_properties INT DEFAULT NULL, min_properties INT DEFAULT NULL, required BOOLEAN DEFAULT NULL, required_if TEXT DEFAULT NULL, forbidden_if TEXT DEFAULT NULL, enum TEXT DEFAULT NULL, all_of TEXT DEFAULT NULL, any_of TEXT DEFAULT NULL, one_of TEXT DEFAULT NULL, description TEXT DEFAULT NULL, default_value VARCHAR(255) DEFAULT NULL, nullable BOOLEAN DEFAULT \'true\', must_be_unique BOOLEAN DEFAULT NULL, case_sensitive BOOLEAN DEFAULT \'true\', read_only BOOLEAN DEFAULT NULL, write_only BOOLEAN DEFAULT NULL, example TEXT DEFAULT NULL, pattern VARCHAR(255) DEFAULT NULL, deprecated BOOLEAN DEFAULT NULL, min_date VARCHAR(255) DEFAULT NULL, max_date VARCHAR(255) DEFAULT NULL, max_file_size INT DEFAULT NULL, min_file_size INT DEFAULT NULL, file_types TEXT DEFAULT NULL, persist_to_gateway BOOLEAN DEFAULT NULL, searchable BOOLEAN DEFAULT \'false\', sortable BOOLEAN DEFAULT \'false\', trigger_parent_events BOOLEAN DEFAULT \'false\', cascade_delete BOOLEAN DEFAULT NULL, allow_cascade BOOLEAN DEFAULT NULL, object_config TEXT DEFAULT NULL, immutable BOOLEAN DEFAULT NULL, unsetable BOOLEAN DEFAULT NULL, may_be_orphaned BOOLEAN DEFAULT NULL, schema_column VARCHAR(255) DEFAULT NULL, inversed_by_property_name VARCHAR(255) DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, reference VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FA7AEFFB81257D5D ON attribute (entity_id)');
        $this->addSql('CREATE INDEX IDX_FA7AEFFB13667EE0 ON attribute (search_partial_id)');
        $this->addSql('CREATE INDEX IDX_FA7AEFFB232D562B ON attribute (object_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FA7AEFFBA0ACC089 ON attribute (inversed_by_id)');
        $this->addSql('COMMENT ON COLUMN attribute.required_if IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN attribute.forbidden_if IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN attribute.enum IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN attribute.all_of IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN attribute.any_of IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN attribute.one_of IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN attribute.file_types IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN attribute.object_config IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE audit_trail (id UUID NOT NULL, note TEXT DEFAULT NULL, application VARCHAR(255) DEFAULT NULL, request VARCHAR(255) DEFAULT NULL, username VARCHAR(255) DEFAULT NULL, subject VARCHAR(255) DEFAULT NULL, process VARCHAR(255) DEFAULT NULL, data_elements TEXT DEFAULT NULL, data_subjects TEXT DEFAULT NULL, resource VARCHAR(255) DEFAULT NULL, resource_type VARCHAR(255) DEFAULT NULL, route VARCHAR(255) DEFAULT NULL, endpoint VARCHAR(255) DEFAULT NULL, method VARCHAR(10) DEFAULT NULL, accept VARCHAR(255) DEFAULT NULL, content_type VARCHAR(255) DEFAULT NULL, content TEXT DEFAULT NULL, ip VARCHAR(255) DEFAULT NULL, session VARCHAR(255) NOT NULL, headers TEXT NOT NULL, status_code INT DEFAULT NULL, not_found BOOLEAN DEFAULT NULL, forbidden BOOLEAN DEFAULT NULL, ok BOOLEAN DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN audit_trail.data_elements IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN audit_trail.data_subjects IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN audit_trail.headers IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE authentication (id UUID NOT NULL, name VARCHAR(255) NOT NULL, authenticate_url TEXT DEFAULT NULL, token_url TEXT DEFAULT NULL, secret TEXT DEFAULT NULL, client_id TEXT DEFAULT NULL, scopes TEXT DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN authentication.scopes IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE change_log (id UUID NOT NULL, note TEXT DEFAULT NULL, action VARCHAR(8) NOT NULL, logged_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, object_id VARCHAR(64) DEFAULT NULL, object_class VARCHAR(255) NOT NULL, version INT NOT NULL, data TEXT DEFAULT NULL, username VARCHAR(255) DEFAULT NULL, session VARCHAR(255) DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN change_log.data IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE collection_entity (id UUID NOT NULL, source_id UUID DEFAULT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, location_oas VARCHAR(255) DEFAULT NULL, source_url VARCHAR(255) DEFAULT NULL, source_type VARCHAR(255) DEFAULT NULL, source_branch VARCHAR(255) DEFAULT NULL, test_data_location VARCHAR(255) DEFAULT NULL, load_test_data BOOLEAN DEFAULT \'false\', synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, auto_load BOOLEAN DEFAULT \'false\', prefix VARCHAR(255) DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, plugin VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FC0DBC9E953C1C61 ON collection_entity (source_id)');
        $this->addSql('CREATE TABLE collection_entity_application (collection_entity_id UUID NOT NULL, application_id UUID NOT NULL, PRIMARY KEY(collection_entity_id, application_id))');
        $this->addSql('CREATE INDEX IDX_AFA56947A70DCD3F ON collection_entity_application (collection_entity_id)');
        $this->addSql('CREATE INDEX IDX_AFA569473E030ACD ON collection_entity_application (application_id)');
        $this->addSql('CREATE TABLE collection_entity_endpoint (collection_entity_id UUID NOT NULL, endpoint_id UUID NOT NULL, PRIMARY KEY(collection_entity_id, endpoint_id))');
        $this->addSql('CREATE INDEX IDX_6A0BA8FDA70DCD3F ON collection_entity_endpoint (collection_entity_id)');
        $this->addSql('CREATE INDEX IDX_6A0BA8FD21AF7E36 ON collection_entity_endpoint (endpoint_id)');
        $this->addSql('CREATE TABLE collection_entity_entity (collection_entity_id UUID NOT NULL, entity_id UUID NOT NULL, PRIMARY KEY(collection_entity_id, entity_id))');
        $this->addSql('CREATE INDEX IDX_11C4102AA70DCD3F ON collection_entity_entity (collection_entity_id)');
        $this->addSql('CREATE INDEX IDX_11C4102A81257D5D ON collection_entity_entity (entity_id)');
        $this->addSql('CREATE TABLE contract (id UUID NOT NULL, application_id UUID NOT NULL, signing_user VARCHAR(36) NOT NULL, grants TEXT NOT NULL, user_signed_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, app_signed_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E98F28593E030ACD ON contract (application_id)');
        $this->addSql('COMMENT ON COLUMN contract.grants IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE cronjob (id UUID NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, crontab VARCHAR(255) NOT NULL, throws TEXT NOT NULL, data TEXT DEFAULT NULL, last_run TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, next_run TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_enabled BOOLEAN DEFAULT \'true\', date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN cronjob.throws IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN cronjob.data IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE cronjob_log (id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE dashboard_card (id UUID NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, type VARCHAR(255) NOT NULL, entity VARCHAR(255) NOT NULL, entity_id UUID NOT NULL, ordering INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE document (id UUID NOT NULL, object_id UUID DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, route VARCHAR(255) NOT NULL, data VARCHAR(255) NOT NULL, data_id VARCHAR(255) NOT NULL, document_creation_service VARCHAR(255) NOT NULL, document_type VARCHAR(255) NOT NULL, content_type VARCHAR(255) DEFAULT NULL, content TEXT DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D8698A76232D562B ON document (object_id)');
        $this->addSql('CREATE TABLE endpoint (id UUID NOT NULL, entity_id UUID DEFAULT NULL, proxy_id UUID DEFAULT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, path_regex VARCHAR(255) DEFAULT NULL, method VARCHAR(255) DEFAULT NULL, tag VARCHAR(255) DEFAULT NULL, path TEXT NOT NULL, logging_config TEXT DEFAULT NULL, operation_type VARCHAR(255) DEFAULT NULL, tags TEXT DEFAULT NULL, path_array TEXT DEFAULT NULL, methods TEXT DEFAULT NULL, throws TEXT DEFAULT NULL, status BOOLEAN DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, default_content_type TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C4420F7B81257D5D ON endpoint (entity_id)');
        $this->addSql('CREATE INDEX IDX_C4420F7BDB26A4E ON endpoint (proxy_id)');
        $this->addSql('COMMENT ON COLUMN endpoint.path IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN endpoint.logging_config IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN endpoint.tags IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN endpoint.path_array IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN endpoint.methods IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN endpoint.throws IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE endpoint_entity (endpoint_id UUID NOT NULL, entity_id UUID NOT NULL, PRIMARY KEY(endpoint_id, entity_id))');
        $this->addSql('CREATE INDEX IDX_333EE79721AF7E36 ON endpoint_entity (endpoint_id)');
        $this->addSql('CREATE INDEX IDX_333EE79781257D5D ON endpoint_entity (entity_id)');
        $this->addSql('CREATE TABLE file (id UUID NOT NULL, value_id UUID DEFAULT NULL, name VARCHAR(255) NOT NULL, extension VARCHAR(255) NOT NULL, mime_type VARCHAR(255) NOT NULL, size VARCHAR(255) NOT NULL, base64 TEXT NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8C9F3610F920BBA2 ON file (value_id)');
        $this->addSql('CREATE TABLE handler (id UUID NOT NULL, entity_id UUID DEFAULT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, methods TEXT NOT NULL, sequence INT NOT NULL, conditions VARCHAR(255) DEFAULT \'{}\' NOT NULL, translations_in TEXT DEFAULT NULL, mapping_in TEXT DEFAULT NULL, skeleton_in TEXT DEFAULT NULL, skeleton_out TEXT DEFAULT NULL, mapping_out TEXT DEFAULT NULL, translations_out TEXT DEFAULT NULL, template_type VARCHAR(255) DEFAULT NULL, template TEXT DEFAULT NULL, proxy_gateway VARCHAR(255) DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, method_overrides TEXT DEFAULT NULL, prefix VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_939715CD81257D5D ON handler (entity_id)');
        $this->addSql('COMMENT ON COLUMN handler.methods IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN handler.translations_in IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN handler.mapping_in IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN handler.skeleton_in IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN handler.skeleton_out IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN handler.mapping_out IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN handler.translations_out IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN handler.method_overrides IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE handler_endpoint (handler_id UUID NOT NULL, endpoint_id UUID NOT NULL, PRIMARY KEY(handler_id, endpoint_id))');
        $this->addSql('CREATE INDEX IDX_26CCBD14A6E82043 ON handler_endpoint (handler_id)');
        $this->addSql('CREATE INDEX IDX_26CCBD1421AF7E36 ON handler_endpoint (endpoint_id)');
        $this->addSql('CREATE TABLE log (id UUID NOT NULL, entity_id UUID DEFAULT NULL, endpoint_id UUID DEFAULT NULL, gateway_id UUID DEFAULT NULL, handler_id UUID DEFAULT NULL, type VARCHAR(255) NOT NULL, call_id UUID NOT NULL, request_method VARCHAR(255) NOT NULL, request_headers TEXT NOT NULL, request_query TEXT NOT NULL, request_path_info VARCHAR(255) NOT NULL, request_languages TEXT NOT NULL, request_server TEXT NOT NULL, request_content TEXT NOT NULL, response_status VARCHAR(255) DEFAULT NULL, response_status_code INT DEFAULT NULL, response_headers TEXT DEFAULT NULL, response_content TEXT DEFAULT NULL, user_id VARCHAR(255) DEFAULT NULL, session VARCHAR(255) NOT NULL, session_values TEXT NOT NULL, response_time INT NOT NULL, route_name VARCHAR(255) DEFAULT NULL, route_parameters TEXT DEFAULT NULL, object_id VARCHAR(255) DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8F3F68C581257D5D ON log (entity_id)');
        $this->addSql('CREATE INDEX IDX_8F3F68C521AF7E36 ON log (endpoint_id)');
        $this->addSql('CREATE INDEX IDX_8F3F68C5577F8E00 ON log (gateway_id)');
        $this->addSql('CREATE INDEX IDX_8F3F68C5A6E82043 ON log (handler_id)');
        $this->addSql('COMMENT ON COLUMN log.request_headers IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN log.request_query IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN log.request_languages IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN log.request_server IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN log.response_headers IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN log.session_values IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN log.route_parameters IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE mapping (id UUID NOT NULL, reference VARCHAR(255) DEFAULT NULL, version VARCHAR(255) DEFAULT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, mapping TEXT NOT NULL, unset TEXT DEFAULT NULL, cast_column TEXT DEFAULT NULL, pass_trough BOOLEAN DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN mapping.mapping IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN mapping.unset IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN mapping.cast_column IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE object_entity (id UUID NOT NULL, application_id UUID DEFAULT NULL, organization_id UUID DEFAULT NULL, entity_id UUID DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, self VARCHAR(255) DEFAULT NULL, external_id VARCHAR(255) DEFAULT NULL, uri VARCHAR(255) DEFAULT NULL, owner VARCHAR(255) DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_40A8E4683E030ACD ON object_entity (application_id)');
        $this->addSql('CREATE INDEX IDX_40A8E46832C8A3DE ON object_entity (organization_id)');
        $this->addSql('CREATE INDEX IDX_40A8E46881257D5D ON object_entity (entity_id)');
        $this->addSql('CREATE TABLE object_entity_value (object_entity_id UUID NOT NULL, value_id UUID NOT NULL, PRIMARY KEY(object_entity_id, value_id))');
        $this->addSql('CREATE INDEX IDX_56F9E4AAC29A42DA ON object_entity_value (object_entity_id)');
        $this->addSql('CREATE INDEX IDX_56F9E4AAF920BBA2 ON object_entity_value (value_id)');
        $this->addSql('CREATE TABLE organization (id UUID NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE security_group (id UUID NOT NULL, parent_id UUID DEFAULT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, scopes TEXT NOT NULL, anonymous BOOLEAN DEFAULT \'false\' NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_817CA76F727ACA70 ON security_group (parent_id)');
        $this->addSql('COMMENT ON COLUMN security_group.scopes IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE security_group_user (security_group_id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY(security_group_id, user_id))');
        $this->addSql('CREATE INDEX IDX_641B5F4C9D3F5E95 ON security_group_user (security_group_id)');
        $this->addSql('CREATE INDEX IDX_641B5F4CA76ED395 ON security_group_user (user_id)');
        $this->addSql('CREATE TABLE soap (id UUID NOT NULL, to_entity_id UUID DEFAULT NULL, from_entity_id UUID DEFAULT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, type VARCHAR(255) NOT NULL, request TEXT DEFAULT NULL, request_skeleton TEXT NOT NULL, request_hydration TEXT DEFAULT NULL, response TEXT DEFAULT NULL, response_skeleton TEXT NOT NULL, response_hydration TEXT DEFAULT NULL, zaaktype VARCHAR(255) DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_37A677A9B086AA2C ON soap (to_entity_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_37A677A991B9E8E7 ON soap (from_entity_id)');
        $this->addSql('COMMENT ON COLUMN soap.request_skeleton IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN soap.request_hydration IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN soap.response_skeleton IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN soap.response_hydration IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE translation (id UUID NOT NULL, translation_table VARCHAR(255) NOT NULL, translate_from VARCHAR(255) NOT NULL, translate_to VARCHAR(255) NOT NULL, language VARCHAR(255) DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE unread (id UUID NOT NULL, object_id UUID NOT NULL, user_id VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_753C6A86232D562B ON unread (object_id)');
        $this->addSql('CREATE TABLE "user" (id UUID NOT NULL, organisation_id UUID NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, password VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, locale VARCHAR(255) DEFAULT NULL, person VARCHAR(255) DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8D93D6499E6B1585 ON "user" (organisation_id)');
        $this->addSql('CREATE TABLE user_application (user_id UUID NOT NULL, application_id UUID NOT NULL, PRIMARY KEY(user_id, application_id))');
        $this->addSql('CREATE INDEX IDX_D401454A76ED395 ON user_application (user_id)');
        $this->addSql('CREATE INDEX IDX_D4014543E030ACD ON user_application (application_id)');
        $this->addSql('CREATE TABLE value (id UUID NOT NULL, attribute_id UUID NOT NULL, object_entity_id UUID DEFAULT NULL, uri VARCHAR(255) DEFAULT NULL, string_value TEXT DEFAULT NULL, integer_value INT DEFAULT NULL, number_value DOUBLE PRECISION DEFAULT NULL, boolean_value BOOLEAN DEFAULT NULL, array_value TEXT DEFAULT NULL, simple_array_value TEXT DEFAULT NULL, date_time_value TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modified TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1D775834B6E62EFA ON value (attribute_id)');
        $this->addSql('CREATE INDEX IDX_1D775834C29A42DA ON value (object_entity_id)');
        $this->addSql('COMMENT ON COLUMN value.array_value IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN value.simple_array_value IS \'(DC2Type:simple_array)\'');
        $this->addSql('CREATE TABLE messenger_messages (id BIGSERIAL NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('CREATE OR REPLACE FUNCTION notify_messenger_messages() RETURNS TRIGGER AS $$
            BEGIN
                PERFORM pg_notify(\'messenger_messages\', NEW.queue_name::text);
                RETURN NEW;
            END;
        $$ LANGUAGE plpgsql;');
        $this->addSql('DROP TRIGGER IF EXISTS notify_trigger ON messenger_messages;');
        $this->addSql('CREATE TRIGGER notify_trigger AFTER INSERT OR UPDATE ON messenger_messages FOR EACH ROW EXECUTE PROCEDURE notify_messenger_messages();');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC132C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE application_endpoint ADD CONSTRAINT FK_7B79D0683E030ACD FOREIGN KEY (application_id) REFERENCES application (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE application_endpoint ADD CONSTRAINT FK_7B79D06821AF7E36 FOREIGN KEY (endpoint_id) REFERENCES endpoint (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attribute ADD CONSTRAINT FK_FA7AEFFB81257D5D FOREIGN KEY (entity_id) REFERENCES entity (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attribute ADD CONSTRAINT FK_FA7AEFFB13667EE0 FOREIGN KEY (search_partial_id) REFERENCES entity (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attribute ADD CONSTRAINT FK_FA7AEFFB232D562B FOREIGN KEY (object_id) REFERENCES entity (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attribute ADD CONSTRAINT FK_FA7AEFFBA0ACC089 FOREIGN KEY (inversed_by_id) REFERENCES attribute (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE collection_entity ADD CONSTRAINT FK_FC0DBC9E953C1C61 FOREIGN KEY (source_id) REFERENCES gateway (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE collection_entity_application ADD CONSTRAINT FK_AFA56947A70DCD3F FOREIGN KEY (collection_entity_id) REFERENCES collection_entity (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE collection_entity_application ADD CONSTRAINT FK_AFA569473E030ACD FOREIGN KEY (application_id) REFERENCES application (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE collection_entity_endpoint ADD CONSTRAINT FK_6A0BA8FDA70DCD3F FOREIGN KEY (collection_entity_id) REFERENCES collection_entity (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE collection_entity_endpoint ADD CONSTRAINT FK_6A0BA8FD21AF7E36 FOREIGN KEY (endpoint_id) REFERENCES endpoint (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE collection_entity_entity ADD CONSTRAINT FK_11C4102AA70DCD3F FOREIGN KEY (collection_entity_id) REFERENCES collection_entity (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE collection_entity_entity ADD CONSTRAINT FK_11C4102A81257D5D FOREIGN KEY (entity_id) REFERENCES entity (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contract ADD CONSTRAINT FK_E98F28593E030ACD FOREIGN KEY (application_id) REFERENCES application (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76232D562B FOREIGN KEY (object_id) REFERENCES entity (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE endpoint ADD CONSTRAINT FK_C4420F7B81257D5D FOREIGN KEY (entity_id) REFERENCES entity (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE endpoint ADD CONSTRAINT FK_C4420F7BDB26A4E FOREIGN KEY (proxy_id) REFERENCES gateway (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE endpoint_entity ADD CONSTRAINT FK_333EE79721AF7E36 FOREIGN KEY (endpoint_id) REFERENCES endpoint (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE endpoint_entity ADD CONSTRAINT FK_333EE79781257D5D FOREIGN KEY (entity_id) REFERENCES entity (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE file ADD CONSTRAINT FK_8C9F3610F920BBA2 FOREIGN KEY (value_id) REFERENCES value (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE handler ADD CONSTRAINT FK_939715CD81257D5D FOREIGN KEY (entity_id) REFERENCES entity (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE handler_endpoint ADD CONSTRAINT FK_26CCBD14A6E82043 FOREIGN KEY (handler_id) REFERENCES handler (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE handler_endpoint ADD CONSTRAINT FK_26CCBD1421AF7E36 FOREIGN KEY (endpoint_id) REFERENCES endpoint (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE log ADD CONSTRAINT FK_8F3F68C581257D5D FOREIGN KEY (entity_id) REFERENCES entity (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE log ADD CONSTRAINT FK_8F3F68C521AF7E36 FOREIGN KEY (endpoint_id) REFERENCES endpoint (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE log ADD CONSTRAINT FK_8F3F68C5577F8E00 FOREIGN KEY (gateway_id) REFERENCES gateway (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE log ADD CONSTRAINT FK_8F3F68C5A6E82043 FOREIGN KEY (handler_id) REFERENCES handler (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE object_entity ADD CONSTRAINT FK_40A8E4683E030ACD FOREIGN KEY (application_id) REFERENCES application (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE object_entity ADD CONSTRAINT FK_40A8E46832C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE object_entity ADD CONSTRAINT FK_40A8E46881257D5D FOREIGN KEY (entity_id) REFERENCES entity (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE object_entity_value ADD CONSTRAINT FK_56F9E4AAC29A42DA FOREIGN KEY (object_entity_id) REFERENCES object_entity (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE object_entity_value ADD CONSTRAINT FK_56F9E4AAF920BBA2 FOREIGN KEY (value_id) REFERENCES value (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE security_group ADD CONSTRAINT FK_817CA76F727ACA70 FOREIGN KEY (parent_id) REFERENCES security_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE security_group_user ADD CONSTRAINT FK_641B5F4C9D3F5E95 FOREIGN KEY (security_group_id) REFERENCES security_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE security_group_user ADD CONSTRAINT FK_641B5F4CA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE soap ADD CONSTRAINT FK_37A677A9B086AA2C FOREIGN KEY (to_entity_id) REFERENCES entity (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE soap ADD CONSTRAINT FK_37A677A991B9E8E7 FOREIGN KEY (from_entity_id) REFERENCES entity (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE unread ADD CONSTRAINT FK_753C6A86232D562B FOREIGN KEY (object_id) REFERENCES object_entity (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D6499E6B1585 FOREIGN KEY (organisation_id) REFERENCES organization (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_application ADD CONSTRAINT FK_D401454A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_application ADD CONSTRAINT FK_D4014543E030ACD FOREIGN KEY (application_id) REFERENCES application (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE value ADD CONSTRAINT FK_1D775834B6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE value ADD CONSTRAINT FK_1D775834C29A42DA FOREIGN KEY (object_entity_id) REFERENCES object_entity (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE action ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE action ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE entity ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE entity ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE entity ALTER gateway_id TYPE UUID');
        $this->addSql('ALTER TABLE entity ALTER gateway_id DROP DEFAULT');
        $this->addSql('ALTER TABLE entity ADD CONSTRAINT FK_E284468577F8E00 FOREIGN KEY (gateway_id) REFERENCES gateway (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gateway ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE gateway ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE property ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE property ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE property ALTER endpoint_id TYPE UUID');
        $this->addSql('ALTER TABLE property ALTER endpoint_id DROP DEFAULT');
        $this->addSql('ALTER TABLE property ADD CONSTRAINT FK_8BF21CDE21AF7E36 FOREIGN KEY (endpoint_id) REFERENCES endpoint (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE purpose ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE purpose ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE purpose ALTER contract_id TYPE UUID');
        $this->addSql('ALTER TABLE purpose ALTER contract_id DROP DEFAULT');
        $this->addSql('ALTER TABLE purpose ADD CONSTRAINT FK_B887B3EB2576E0FD FOREIGN KEY (contract_id) REFERENCES contract (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE synchronization ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE synchronization ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE synchronization ALTER entity_id TYPE UUID');
        $this->addSql('ALTER TABLE synchronization ALTER entity_id DROP DEFAULT');
        $this->addSql('ALTER TABLE synchronization ALTER object_id TYPE UUID');
        $this->addSql('ALTER TABLE synchronization ALTER object_id DROP DEFAULT');
        $this->addSql('ALTER TABLE synchronization ALTER action_id TYPE UUID');
        $this->addSql('ALTER TABLE synchronization ALTER action_id DROP DEFAULT');
        $this->addSql('ALTER TABLE synchronization ALTER gateway_id TYPE UUID');
        $this->addSql('ALTER TABLE synchronization ALTER gateway_id DROP DEFAULT');
        $this->addSql('ALTER TABLE synchronization ALTER source_object_id TYPE UUID');
        $this->addSql('ALTER TABLE synchronization ALTER source_object_id DROP DEFAULT');
        $this->addSql('ALTER TABLE synchronization ALTER mapping_id TYPE UUID');
        $this->addSql('ALTER TABLE synchronization ALTER mapping_id DROP DEFAULT');
        $this->addSql('ALTER TABLE synchronization ADD CONSTRAINT FK_8AF3CC3A81257D5D FOREIGN KEY (entity_id) REFERENCES entity (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE synchronization ADD CONSTRAINT FK_8AF3CC3A232D562B FOREIGN KEY (object_id) REFERENCES object_entity (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE synchronization ADD CONSTRAINT FK_8AF3CC3A9D32F035 FOREIGN KEY (action_id) REFERENCES action (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE synchronization ADD CONSTRAINT FK_8AF3CC3A577F8E00 FOREIGN KEY (gateway_id) REFERENCES gateway (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE synchronization ADD CONSTRAINT FK_8AF3CC3A4BB3C5E5 FOREIGN KEY (source_object_id) REFERENCES object_entity (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE synchronization ADD CONSTRAINT FK_8AF3CC3AFABB77CC FOREIGN KEY (mapping_id) REFERENCES mapping (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE application_endpoint DROP CONSTRAINT FK_7B79D0683E030ACD');
        $this->addSql('ALTER TABLE collection_entity_application DROP CONSTRAINT FK_AFA569473E030ACD');
        $this->addSql('ALTER TABLE contract DROP CONSTRAINT FK_E98F28593E030ACD');
        $this->addSql('ALTER TABLE object_entity DROP CONSTRAINT FK_40A8E4683E030ACD');
        $this->addSql('ALTER TABLE user_application DROP CONSTRAINT FK_D4014543E030ACD');
        $this->addSql('ALTER TABLE attribute DROP CONSTRAINT FK_FA7AEFFBA0ACC089');
        $this->addSql('ALTER TABLE value DROP CONSTRAINT FK_1D775834B6E62EFA');
        $this->addSql('ALTER TABLE collection_entity_application DROP CONSTRAINT FK_AFA56947A70DCD3F');
        $this->addSql('ALTER TABLE collection_entity_endpoint DROP CONSTRAINT FK_6A0BA8FDA70DCD3F');
        $this->addSql('ALTER TABLE collection_entity_entity DROP CONSTRAINT FK_11C4102AA70DCD3F');
        $this->addSql('ALTER TABLE purpose DROP CONSTRAINT FK_B887B3EB2576E0FD');
        $this->addSql('ALTER TABLE application_endpoint DROP CONSTRAINT FK_7B79D06821AF7E36');
        $this->addSql('ALTER TABLE collection_entity_endpoint DROP CONSTRAINT FK_6A0BA8FD21AF7E36');
        $this->addSql('ALTER TABLE endpoint_entity DROP CONSTRAINT FK_333EE79721AF7E36');
        $this->addSql('ALTER TABLE handler_endpoint DROP CONSTRAINT FK_26CCBD1421AF7E36');
        $this->addSql('ALTER TABLE log DROP CONSTRAINT FK_8F3F68C521AF7E36');
        $this->addSql('ALTER TABLE property DROP CONSTRAINT FK_8BF21CDE21AF7E36');
        $this->addSql('ALTER TABLE handler_endpoint DROP CONSTRAINT FK_26CCBD14A6E82043');
        $this->addSql('ALTER TABLE log DROP CONSTRAINT FK_8F3F68C5A6E82043');
        $this->addSql('ALTER TABLE synchronization DROP CONSTRAINT FK_8AF3CC3AFABB77CC');
        $this->addSql('ALTER TABLE object_entity_value DROP CONSTRAINT FK_56F9E4AAC29A42DA');
        $this->addSql('ALTER TABLE synchronization DROP CONSTRAINT FK_8AF3CC3A232D562B');
        $this->addSql('ALTER TABLE synchronization DROP CONSTRAINT FK_8AF3CC3A4BB3C5E5');
        $this->addSql('ALTER TABLE unread DROP CONSTRAINT FK_753C6A86232D562B');
        $this->addSql('ALTER TABLE value DROP CONSTRAINT FK_1D775834C29A42DA');
        $this->addSql('ALTER TABLE application DROP CONSTRAINT FK_A45BDDC132C8A3DE');
        $this->addSql('ALTER TABLE object_entity DROP CONSTRAINT FK_40A8E46832C8A3DE');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D6499E6B1585');
        $this->addSql('ALTER TABLE security_group DROP CONSTRAINT FK_817CA76F727ACA70');
        $this->addSql('ALTER TABLE security_group_user DROP CONSTRAINT FK_641B5F4C9D3F5E95');
        $this->addSql('ALTER TABLE security_group_user DROP CONSTRAINT FK_641B5F4CA76ED395');
        $this->addSql('ALTER TABLE user_application DROP CONSTRAINT FK_D401454A76ED395');
        $this->addSql('ALTER TABLE file DROP CONSTRAINT FK_8C9F3610F920BBA2');
        $this->addSql('ALTER TABLE object_entity_value DROP CONSTRAINT FK_56F9E4AAF920BBA2');
        $this->addSql('DROP TABLE action_handler');
        $this->addSql('DROP TABLE application');
        $this->addSql('DROP TABLE application_endpoint');
        $this->addSql('DROP TABLE attribute');
        $this->addSql('DROP TABLE audit_trail');
        $this->addSql('DROP TABLE authentication');
        $this->addSql('DROP TABLE change_log');
        $this->addSql('DROP TABLE collection_entity');
        $this->addSql('DROP TABLE collection_entity_application');
        $this->addSql('DROP TABLE collection_entity_endpoint');
        $this->addSql('DROP TABLE collection_entity_entity');
        $this->addSql('DROP TABLE contract');
        $this->addSql('DROP TABLE cronjob');
        $this->addSql('DROP TABLE cronjob_log');
        $this->addSql('DROP TABLE dashboard_card');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE endpoint');
        $this->addSql('DROP TABLE endpoint_entity');
        $this->addSql('DROP TABLE file');
        $this->addSql('DROP TABLE handler');
        $this->addSql('DROP TABLE handler_endpoint');
        $this->addSql('DROP TABLE log');
        $this->addSql('DROP TABLE mapping');
        $this->addSql('DROP TABLE object_entity');
        $this->addSql('DROP TABLE object_entity_value');
        $this->addSql('DROP TABLE organization');
        $this->addSql('DROP TABLE security_group');
        $this->addSql('DROP TABLE security_group_user');
        $this->addSql('DROP TABLE soap');
        $this->addSql('DROP TABLE translation');
        $this->addSql('DROP TABLE unread');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_application');
        $this->addSql('DROP TABLE value');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE entity DROP CONSTRAINT FK_E284468577F8E00');
        $this->addSql('ALTER TABLE entity ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE entity ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE entity ALTER gateway_id TYPE UUID');
        $this->addSql('ALTER TABLE entity ALTER gateway_id DROP DEFAULT');
        $this->addSql('ALTER TABLE action ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE action ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE synchronization DROP CONSTRAINT FK_8AF3CC3A81257D5D');
        $this->addSql('ALTER TABLE synchronization DROP CONSTRAINT FK_8AF3CC3A9D32F035');
        $this->addSql('ALTER TABLE synchronization DROP CONSTRAINT FK_8AF3CC3A577F8E00');
        $this->addSql('ALTER TABLE synchronization ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE synchronization ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE synchronization ALTER entity_id TYPE UUID');
        $this->addSql('ALTER TABLE synchronization ALTER entity_id DROP DEFAULT');
        $this->addSql('ALTER TABLE synchronization ALTER object_id TYPE UUID');
        $this->addSql('ALTER TABLE synchronization ALTER object_id DROP DEFAULT');
        $this->addSql('ALTER TABLE synchronization ALTER action_id TYPE UUID');
        $this->addSql('ALTER TABLE synchronization ALTER action_id DROP DEFAULT');
        $this->addSql('ALTER TABLE synchronization ALTER gateway_id TYPE UUID');
        $this->addSql('ALTER TABLE synchronization ALTER gateway_id DROP DEFAULT');
        $this->addSql('ALTER TABLE synchronization ALTER source_object_id TYPE UUID');
        $this->addSql('ALTER TABLE synchronization ALTER source_object_id DROP DEFAULT');
        $this->addSql('ALTER TABLE synchronization ALTER mapping_id TYPE UUID');
        $this->addSql('ALTER TABLE synchronization ALTER mapping_id DROP DEFAULT');
        $this->addSql('ALTER TABLE property ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE property ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE property ALTER endpoint_id TYPE UUID');
        $this->addSql('ALTER TABLE property ALTER endpoint_id DROP DEFAULT');
        $this->addSql('ALTER TABLE purpose ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE purpose ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE purpose ALTER contract_id TYPE UUID');
        $this->addSql('ALTER TABLE purpose ALTER contract_id DROP DEFAULT');
        $this->addSql('ALTER TABLE gateway ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE gateway ALTER id DROP DEFAULT');
    }
}
