| API               | Endpoint/object             | Get (collection) | Get (Single) | Post | Put | Patch | Wordgebruikt voor                   | Documentaite                                                                                                                                                                                                                                                                                                                 |
| ----------------- | --------------------------- | ---------------- | ------------ | ---- | --- | ----- | ----------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Contactmomenten   | ContactMoment               | x                | x            | x    | x   | x     | Nodig voor verwerken contactmoment  | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/ContactMoment-contactmomenten-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/ContactMoment-contactmomenten-collection)               |
| Contactmomenten   | KlantContactMoment          | x                | x            | x    | x   | x     | Nodig voor verwerken contactmoment  | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/KlantContactMoment-contactmomenten-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/KlantContactMoment-contactmomenten-collection)     |
| Contactmomenten   | ObjectContactMoment         | x                | x            | x    | x   | x     | Nodig voor verwerken contactmoment  | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/ObjectContactMoment-contactmomenten-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/ObjectContactMoment-contactmomenten-collection)   |
| Klanten API       | Klant                       | x                | x            | x    | x   | x     | Nodig voor verwerken contactmoment  | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/Klant-Klanten-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/Klant-Klanten-collection)                                               |
| Verzoeken         | Verzoek                     | X                | X            | nvt  | nvt | nvt   | Nodig voor weergeven zaakinformatie | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/Verzoek-verzoeken-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/Verzoek-verzoeken-collection)                                       |
| Verzoeken         | ObjectVerzoek               | X                | X            | nvt  | nvt | nvt   | Nodig voor weergeven zaakinformatie | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/ObjectVerzoek-verzoeken-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/ObjectVerzoek-verzoeken-collection)                           |
| Verzoeken         | VerzoekContactMoment        | x                | x            | x    | x   | x     | Nodig voor verwerken contactmoment  | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/VerzoekContactMoment-verzoeken-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/VerzoekContactMoment-verzoeken-collection)             |
| Verzoeken         | VerzoekProduct              | X                | X            | nvt  | nvt | nvt   | Nodig voor weergeven zaakinformatie | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/VerzoekProduct-verzoeken-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/VerzoekProduct-verzoeken-collection)                         |
| Verzoeken         | VerzoekInformatieObject     | X                | X            | nvt  | nvt | nvt   | Nodig voor weergeven zaakinformatie | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/VerzoekInformatieObject-verzoeken-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/VerzoekInformatieObject-verzoeken-collection)       |
| Verzoeken         | KlantVerzoek                | X                | X            | nvt  | nvt | nvt   | Nodig voor verwerken contactmoment  | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/KlantVerzoek-verzoeken-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/KlantVerzoek-verzoeken-collection)                             |
| ZRC               | ZaakVerzoek                 | X                | X            | nvt  | nvt | nvt   | Nodig voor weergeven zaakinformatie | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/ZaakVerzoek-zrc-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/ZaakVerzoek-zrc-collection)                                           |
| ZRC               | Rol                         | X                | X            | nvt  | nvt | nvt   | Nodig voor weergeven zaakinformatie | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/Rol-zrc-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/Rol-zrc-collection)                                                           |
| ZRC               | KlantContact                | x                | x            | x    | x   | x     | Nodig voor verwerken contactmoment  | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/KlantContact-zrc-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/KlantContact-zrc-collection)                                         |
| ZRC               | ZaakBesluit                 | X                | X            | nvt  | nvt | nvt   | Nodig voor weergeven zaakinformatie | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/ZaakBesluit-zrc-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/ZaakBesluit-zrc-collection)                                           |
|                   | ZaakContactmoment           | x                | x            | x    | x   | x     | Nodig voor verwerken contactmoment  | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/ZaakContactMoment-zrc-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/ZaakContactMoment-zrc-collection)                               |
| ZRC               | ZaakInformatieObject        | X                | X            | nvt  | nvt | nvt   | Nodig voor weergeven zaakinformatie | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/ZaakInformatieObject-zrc-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/ZaakInformatieObject-zrc-collection)                         |
| ZRC               | Resultaat                   | X                | X            | nvt  | nvt | nvt   | Nodig voor weergeven zaakinformatie | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/Resultaat-zrc-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/Resultaat-zrc-collection)                                               |
| ZRC               | Status                      | X                | X            | nvt  | nvt | nvt   | Nodig voor weergeven zaakinformatie | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/Status-zrc-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/Status-zrc-collection)                                                     |
| ZRC               | ZaakEigenschap              | X                | X            | nvt  | nvt | nvt   | Nodig voor weergeven zaakinformatie | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/ZaakEigenschap-zrc-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/ZaakEigenschap-zrc-collection)                                     |
| ZRC               | ZaakObject                  | X                | X            | nvt  | nvt | nvt   | Nodig voor weergeven zaakinformatie | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/ZaakObject-zrc-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/ZaakObject-zrc-collection)                                             |
| ZRC               | Zaak                        | x                | x            | x    | x   | x     | Nodig voor verwerken contactmoment  | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/Zaak-zrc-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/Zaak-zrc-collection)                                                         |
| ZTC               | BesluitType                 | X                | X            | nvt  | nvt | nvt   | Nodig voor weergeven zaakinformatie | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/BesluitType-ZTC-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/BesluitType-ZTC-collection)                                           |
| ZTC               | Eigenschap                  | X                | X            | nvt  | nvt | nvt   | Nodig voor weergeven zaakinformatie | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/Eigenschap-ZTC-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/Eigenschap-ZTC-collection)                                             |
| ZTC               | ResultaatType               | X                | X            | nvt  | nvt | nvt   | Nodig voor weergeven zaakinformatie | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/ResultaatType-ZTC-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/ResultaatType-ZTC-collection)                                       |
| ZTC               | Catalogus                   | X                | X            | nvt  | nvt | nvt   | Nodig voor weergeven zaakinformatie | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/Catalogus-ZTC-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/Catalogus-ZTC-collection)                                               |
| ZTC               | ZaakType                    | X                | X            | nvt  | nvt | nvt   | Nodig voor weergeven zaakinformatie | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/ZaakType-ZTC-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/ZaakType-ZTC-collection)                                                 |
| ZTC               | InformatieObjetType         | X                | X            | nvt  | nvt | nvt   | Nodig voor weergeven zaakinformatie | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/InformatieObjectType-ZTC-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/InformatieObjectType-ZTC-collection)                         |
| ZTC               | ZaakTypeInformatieObject    | X                | X            | nvt  | nvt | nvt   | Nodig voor weergeven zaakinformatie | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/InformatieObjectType-ZTC-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/InformatieObjectType-ZTC-collection)                         |
| ZTC               | RolType                     | X                | X            | nvt  | nvt | nvt   | Nodig voor weergeven zaakinformatie | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/RolType-ZTC-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/RolType-ZTC-collection)                                                   |
| ZTC               | StatusType                  | X                | X            | nvt  | nvt | nvt   | Nodig voor weergeven zaakinformatie | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/StatusType-ZTC-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/StatusType-ZTC-collection)                                             |
| DRC               | EnkelvoudigInformatieObject | X                | X            | nvt  | nvt | nvt   | Nodig voor weergeven zaakinformatie | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/EnkelvoudigInformatieObject-DRC-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/EnkelvoudigInformatieObject-DRC-collection)           |
| DRC               | ObjectInforamtieObject      | X                | X            | nvt  | nvt | nvt   | Nodig voor weergeven zaakinformatie | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/ObjectInformatieObject-DRC-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/ObjectInformatieObject-DRC-collection)                     |
| BRC               | BesluitInformatieObject     | X                | X            | nvt  | nvt | nvt   | Nodig voor weergeven zaakinformatie | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/BesluitInformatieObject-brc-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/BesluitInformatieObject-brc-collection)                   |
| BRC               | Besluit                     | X                | X            | nvt  | nvt | nvt   | Nodig voor weergeven zaakinformatie | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/Besluit-brc-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/Besluit-brc-collection)                                                   |
| Referentielijsten | CommunicaiteKanaal          | X                | X            | nvt  | nvt | nvt   | Nodig voor weergeven contectmometn  | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/CommunicatieKanaal-Referentielijsten-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/CommunicatieKanaal-Referentielijsten-collection) |
| Referentielijsten | ProcesType                  | nvt              | nvt          | nvt  | nvt | nvt   | nvt.                                |                                                                                                                                                                                                                                                                                                                              |
| Referentielijsten | Resultaat                   | x                | X            | nvt  | nvt | nvt   | Nodig voor weergeven zaakinformatie | [https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/Resultaat-Referentielijsten-collection](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/Resultaat-Referentielijsten-collection)                   |
|                   |                             |                  |              |      |     |       |                                     |                                                                                                                                                                                                                                                                                                                              |
|                   |                             |                  |              |      |     |       |                                     |                                                                                                                                                                                                                                                                                                                              |
|                   | Total calls                 | 96               |              |      |     |       |                                     |
