controllers:
    resource: ../../src/Controller/
    type: annotation
    
commongateway_controller:
    resource: ../../vendor/commongateway/corebundle/Controller/
    type: annotation  

kernel:
    resource: ../../src/Kernel.php
    type: annotation
