apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "commonground-gateway.fullname" . }}-runner
  labels:
    {{- include "commonground-gateway.labels" . | nindent 4 }}
spec:
  # this cronjob runs every 10 minutes https://crontab.guru/#*_*_*_*_*
  schedule: "{{ .Values.config.crontab }}"
  jobTemplate:
    spec:
      template:
          spec:
                {{- with .Values.imagePullSecrets }}
              imagePullSecrets:
                {{- toYaml . | nindent 8 }}
                {{- end }}
              serviceAccountName: {{ include "commonground-gateway.serviceAccountName" . }}
              securityContext:
                {{- toYaml .Values.podSecurityContext | nindent 16 }}
              volumes:
                  - name: dependencies
                    secret:
                        secretName: "{{ include "commonground-gateway.fullname" . }}-dependencies"
                        defaultMode: 420
                  - name: app-certificates
                    secret:
                        {{ if .Values.security.certificate.existingSecret }}
                        secretName: {{ .Values.security.certificate.existingSecret }}
                        {{ else }}
                        secretName: {{ include "commonground-gateway.fullname" . }}-certificate
                        {{ end }}
                        defaultMode: 420
                  {{- if .Values.security.saml.enabled }}
                  - name: idp-certificate
                    secret:
                        {{ if .Values.security.saml.idp.certificate.existingSecret }}
                        secretName: {{ .Values.security.saml.idp.certificate.existingSecret }}
                        {{ else }}
                        secretName: {{ include "commonground-gateway.fullname" . }}-idpcertificate
                        {{ end }}
                        defaultMode: 420
                  {{- end }}
                  {{- if .Values.fixtures }}
                  - name: fixtures
                    configMap:
                        name: {{ include "commonground-gateway.fullname" . }}-fixtures
                        defaultMode: 420
                {{- end }}
        
              containers:
                  - name: {{ include "commonground-gateway.fullname" . }}-php
                    image: "{{ .Values.php.repository }}:{{ .Values.php.tag | default .Chart.AppVersion }}"
                    imagePullPolicy: {{ .Values.php.pullPolicy }}
                    ports:
                        - containerPort: 9000
                    volumeMounts:
                        - mountPath: /srv/api/config/packages/dependencies.yaml
                          subPath: dependencies.yaml
                          name: dependencies
                          readOnly: true
                        - mountPath: /var/run/certs
                          name: app-certificates
                          readOnly: true
                        {{- if .Values.security.saml.enabled }}
                        - mountPath: /var/run/idp
                          name: idp-certificate
                          readOnly: true
                        {{- end }}
                        {{- if .Values.fixtures }}
                        - mountPath: /srv/api/fixtures
                          name: fixtures
                          readOnly: true
                      {{- end }}
                    args:
                        - bin/console
                        - cronjob:command
                    env:
                        - name: APP_ENV
                          value: {{ .Values.config.env }}
                        - name: APP_AUTH
                          valueFrom:
                              configMapKeyRef:
                                  key: auth-enabled
                                  name: {{ include "commonground-gateway.fullname" . }}
                        - name: AUTH_ENABLED
                          value: 'true'
                        - name: APP_REPRO
                          value: 'https://github.com/ConductionNL/commonground-gateway'
                        - name: TRUSTED_HOSTS
                          valueFrom:
                              configMapKeyRef:
                                  key: trusted-hosts
                                  name: {{ include "commonground-gateway.fullname" . }}
                        - name: TRUSTED_PROXIES
                          valueFrom:
                              configMapKeyRef:
                                  key: trusted-proxies
                                  name: {{ include "commonground-gateway.fullname" . }}
                        - name: CORS_ALLOW_ORIGIN
                          valueFrom:
                              configMapKeyRef:
                                  key: app-cors-allow-origin
                                  name: {{ include "commonground-gateway.fullname" . }}
                        - name: APP_VERSION
                          valueFrom:
                              configMapKeyRef:
                                  key: app-version
                                  name: {{ include "commonground-gateway.fullname" . }}
                        - name: APP_DEBUG
                          valueFrom:
                              configMapKeyRef:
                                  key: debug
                                  name: {{ include "commonground-gateway.fullname" . }}
                        - name: APP_CACHE
                          valueFrom:
                              configMapKeyRef:
                                  key: cache
                                  name: {{ include "commonground-gateway.fullname" . }}
                        - name: DATABASE_URL
                          valueFrom:
                              secretKeyRef:
                                  key: database-url
                                  name: {{ include "commonground-gateway.fullname" . }}
                        - name: APP_URL
                          valueFrom:
                              configMapKeyRef:
                                  key: url
                                  name: {{ include "commonground-gateway.fullname" . }}
        
                        #RabbitMQ
                        - name: RABBITMQ_HOST
                          valueFrom:
                              configMapKeyRef:
                                  name: {{ template "commonground-gateway.fullname" . }}
                                  key: rabbitmq-host
                        - name: RABBITMQ_PORT
                          valueFrom:
                              configMapKeyRef:
                                  name: {{ template "commonground-gateway.fullname" . }}
                                  key: rabbitmq-port
                        - name: RABBITMQ_USERNAME
                          valueFrom:
                              secretKeyRef:
                                  name: {{ template "commonground-gateway.fullname" . }}
                                  key: rabbitmq-username
                        - name: RABBITMQ_PASSWORD
                          valueFrom:
                              secretKeyRef:
                                  name: {{ template "commonground-gateway.fullname" . }}
                                  key: rabbitmq-password
                        #Mailgun # todo: move this to an email plugin (see EmailSubscriber.php)
                        - name: MAILGUN
                          valueFrom:
                              secretKeyRef:
                                  key: mailgun
                                  name: {{ include "commonground-gateway.fullname" . }}
                        {{- if or (and .Values.security.certificate.certificate .Values.security.certificate.privateKey) .Values.security.certificate.existingSecret }}
                        - name: APP_CERT
                          value: '/var/run/certs/tls.crt'
                        - name: APP_KEY
                          value: '/var/run/certs/tls.key'
                        {{- end }}
                        {{- if .Values.redis.enabled }}
                        - name: REDIS_HOST
                          valueFrom:
                              configMapKeyRef:
                                  key: redis-host
                                  name: {{ include "commonground-gateway.fullname" . }}
                        - name: REDIS_PORT
                          valueFrom:
                              configMapKeyRef:
                                  key: redis-port
                                  name: {{ include "commonground-gateway.fullname" . }}
                        {{- end }}
                        - name: SAML_ENABLED
                          valueFrom:
                              secretKeyRef:
                                  key: saml-enabled
                                  name: {{ include "commonground-gateway.fullname" . }}
                        - name: DIGID_ENABLED
                          valueFrom:
                              secretKeyRef:
                                  key: digid-enabled
                                  name: {{ include "commonground-gateway.fullname" . }}
                        {{- if .Values.security.saml.enabled }}
                        - name: SAML_METADATA_LOCATION
                          valueFrom:
                              secretKeyRef:
                                  key: saml-metadata-location
                                  name: {{ include "commonground-gateway.fullname" . }}
                        - name: SAML_SIGN_ON_URL
                          valueFrom:
                              secretKeyRef:
                                  key: saml-single-sign-on-url
                                  name: {{ include "commonground-gateway.fullname" . }}
                        - name: SAML_LOGOUT_URL
                          valueFrom:
                              secretKeyRef:
                                  key: saml-logout-url
                                  name: {{ include "commonground-gateway.fullname" . }}
                        - name: SAML_IDP_CERT
                          value: '/var/run/idp/idp.crt'
                        {{- end }}
                        - name: GITHUB_KEY
                          valueFrom:
                              secretKeyRef:
                                  key: githubKey
                                  name: {{ include "commonground-gateway.fullname" . }}
                        {{- if .Values.security.digid.enabled }}
                        - name: DIGID_METADATA_LOCATION
                          valueFrom:
                              secretKeyRef:
                                  key: digid-metadata-location
                                  name: {{ include "commonground-gateway.fullname" . }}
                        - name: DIGID_ARTIFACT_URL
                          valueFrom:
                              secretKeyRef:
                                  key: digid-artifact-url
                                  name: {{ include "commonground-gateway.fullname" . }}
                        - name: DIGID_SIGN_ON_URL
                          valueFrom:
                              secretKeyRef:
                                  key: digid-single-sign-on-url
                                  name: {{ include "commonground-gateway.fullname" . }}
                        - name: DIGID_LOGOUT_URL
                          valueFrom:
                              secretKeyRef:
                                  key: digid-logout-url
                                  name: {{ include "commonground-gateway.fullname" . }}
                        - name: DIGID_IDP_CERT
                          value: '/var/run/idp/digid_idp.crt'
                        {{-  if and .Values.security.digid.certificate .Values.security.digid.privateKey }}
                        - name: DIGID_CERTIFICATE
                          valueFrom:
                              secretKeyRef:
                                  key: digid-certificate
                                  name: {{ include "commonground-gateway.fullname" . }}
                        - name: DIGID_PRIVATEKEY
                          valueFrom:
                              secretKeyRef:
                                  key: digid-privatekey
                                  name: {{ include "commonground-gateway.fullname" . }}
                        {{- end }}
                      {{- end }}
                {{- with .Values.nodeSelector }}
              nodeSelector:
                {{- toYaml . | nindent 16 }}
                {{- end }}
                {{- with .Values.affinity }}
              affinity:
                {{- toYaml . | nindent 16 }}
                {{- end }}
                {{- with .Values.tolerations }}
              tolerations:
                {{- toYaml . | nindent 16 }}
            {{- end }}
