#############################
# 		"nginx" stage 		#
#############################
# depends on the "php" stage above, and with an litle bit of help from https://github.com/shiphp/nginx-env
FROM nginx:alpine AS api_platform_nginx

# Due to our config we need a copy of the public folder for serving static content
COPY docker/nginx/conf.d/default.conf.template /etc/nginx/templates/default.conf.template
COPY docker/nginx/nginx.conf /etc/nginx/nginx.conf
WORKDIR /srv/api
COPY public public/

RUN chown -R nginx:nginx /srv/api && chmod -R 755 /srv/api && \
        chown -R nginx:nginx /var/cache/nginx && \
        chown -R nginx:nginx /var/log/nginx && \
        chown -R nginx:nginx /etc/nginx/conf.d
RUN touch /var/run/nginx.pid && \
        chown -R nginx:nginx /var/run/nginx.pid
USER nginx
EXPOSE 8080
